GET http://localhost:3001/api/users
###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "pablo",
    "fullName": "Pablo Escobar",
    "password": "123"
}


# GET http://localhost:3001/api/users
# ###

# POST http://localhost:3001/api/users
# Content-Type: application/json

# {
#     "username": "obi-wan",
#     "name": "Obi-Wan Kenobi",
#     "password": "satine"
# }