GET http://localhost:3001/api/users
###

POST http://localhost:3001/api/users
Content-Type: application/json

{
    "username": "test",
    "email": "test@gmail.com",
    "password": "123"
}
###
DELETE http://localhost:3001/api/users


# GET http://localhost:3001/api/users
# ###

# POST http://localhost:3001/api/users
# Content-Type: application/json

# {
#     "username": "obi-wan",
#     "name": "Obi-Wan Kenobi",
#     "password": "satine"
# }